/**
 * Real Data Loader
 * 
 * Loads real PSX data from static JSON files generated by the crawler.
 */

import { CompanyData, IndexData, HistoricalPoint } from '@/types'

/**
 * Fetch JSON data from public directory
 */
async function fetchJSON<T>(filename: string): Promise<T | null> {
  try {
    const response = await fetch(`/data/${filename}`)
    if (!response.ok) {
      console.error(`Failed to fetch ${filename}:`, response.statusText)
      return null
    }
    return await response.json()
  } catch (error) {
    console.error(`Error fetching ${filename}:`, error)
    return null
  }
}

/**
 * Load cement sector companies with real data
 */
export async function loadCementCompanies(): Promise<CompanyData[]> {
  const data = await fetchJSON<{
    companies: Array<{
      symbol: string
      name: string
      currentPrice?: number
      change?: number
      changePercent?: number
      volume?: number
      high?: number
    }>
  }>('cement-sector.json')

  if (!data || !data.companies) {
    console.warn('No cement sector data available, using empty array')
    return []
  }

  return data.companies.map(company => ({
    symbol: company.symbol,
    name: company.name,
    sector: 'Cement',
    price: company.currentPrice || 0,
    change: company.change || 0,
    changePercent: company.changePercent || 0,
    dayHigh: company.high || company.currentPrice || 0,
    dayLow: (company.currentPrice || 0) * 0.98, // Approximate
    week52High: (company.currentPrice || 0) * 1.2, // Approximate
    week52Low: (company.currentPrice || 0) * 0.8, // Approximate
    marketCap: 0, // Not available from API
    pe: 0, // Not available from API
    dividendYield: 0, // Not available from API
    sectorPE: 0, // Not available from API
    volume: company.volume || 0,
    beta: 0, // Not available from API
    eps: 0, // Not available from API
    bookValue: 0, // Not available from API
    roe: 0, // Not available from API
    debtToEquity: 0, // Not available from API
  }))
}

/**
 * Load KSE100 historical data
 */
export async function loadKSE100Historical(): Promise<HistoricalPoint[]> {
  const data = await fetchJSON<{
    data: Array<{
      date: string
      timestamp: number
      open: number
      high: number
      low: number
      close: number
      volume: number
    }>
  }>('kse100-historical.json')

  if (!data || !data.data) {
    console.warn('No KSE100 historical data available')
    return []
  }

  return data.data.map(point => ({
    timestamp: new Date(point.date),
    value: point.close,
    open: point.open,
    high: point.high,
    low: point.low,
    close: point.close,
    volume: point.volume,
  }))
}

/**
 * Load KSE100 index data
 */
export async function loadKSE100Index(): Promise<IndexData | null> {
  const data = await fetchJSON<{
    symbol: string
    statistics: {
      latest: number
      change: number
      changePercent: number
      high: number
      low: number
      avgVolume: number
    }
    data: Array<{
      date: string
      close: number
      volume: number
    }>
  }>('kse100-historical.json')

  if (!data || !data.statistics) {
    console.warn('No KSE100 index data available')
    return null
  }

  const stats = data.statistics
  const historicalData = data.data || []

  return {
    symbol: 'KSE100',
    name: 'KSE 100 Index',
    value: stats.latest,
    change: stats.change,
    changePercent: stats.changePercent,
    high: stats.high,
    low: stats.low,
    open: stats.latest, // Approximate
    close: stats.latest,
    volume: stats.avgVolume,
    marketCap: 0, // Not available
    timestamp: new Date(),
    historicalData: historicalData.map(point => ({
      timestamp: new Date(point.date),
      value: point.close,
      open: point.close,
      high: point.close,
      low: point.close,
      close: point.close,
      volume: point.volume,
    })),
  }
}

/**
 * Load all companies grouped by sector
 */
export async function loadCompaniesBySector(): Promise<Record<string, CompanyData[]>> {
  const data = await fetchJSON<{
    sectors: Record<string, Array<{
      symbol: string
      name: string
      isGEM: boolean
    }>>
  }>('companies.json')

  if (!data || !data.sectors) {
    console.warn('No companies data available')
    return {}
  }

  // Transform to CompanyData format
  const result: Record<string, CompanyData[]> = {}

  for (const [sector, companies] of Object.entries(data.sectors)) {
    result[sector] = companies.map(company => ({
      symbol: company.symbol,
      name: company.name,
      sector,
      price: 0, // Would need individual stock data
      change: 0,
      changePercent: 0,
      dayHigh: 0,
      dayLow: 0,
      week52High: 0,
      week52Low: 0,
      marketCap: 0,
      pe: 0,
      dividendYield: 0,
      sectorPE: 0,
      volume: 0,
      beta: 0,
      eps: 0,
      bookValue: 0,
      roe: 0,
      debtToEquity: 0,
    }))
  }

  return result
}

/**
 * Get last updated timestamp from data files
 */
export async function getLastUpdated(): Promise<Date | null> {
  const data = await fetchJSON<{ lastUpdated: string }>('cement-sector.json')
  
  if (data && data.lastUpdated) {
    return new Date(data.lastUpdated)
  }
  
  return null
}

